[package]
name = "hid_send"
version = "0.1.0"
authors = ["Julia <leoherbsthofer@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.8"
hidapi = "1.2.5"